image: nixpkgs/nix:nixos-20.03

stages:
  - build

nixos-unstable:
  stage: build
  script: NIX_PATH=channel:$NIXPKGS_CHANNEL nix-shell --run ./.gitlab-ci.sh
  variables:
    NIXPKGS_CHANNEL: nixos-unstable
    IMAGE_TAG: latest

nixos-20.03:
  stage: build
  script: NIX_PATH=channel:$NIXPKGS_CHANNEL nix-shell --run ./.gitlab-ci.sh
  variables:
    NIXPKGS_CHANNEL: nixos-20.03
