stages:
  - build

build:
  stage: build
  image: nixpkgs/nix:nixos-21.05
  script: nix-shell --run ./ci.sh
  parallel:
    matrix:
      - NIXPKGS_CHANNEL: nixos-unstable
        IMAGE_TAG: latest
      - NIXPKGS_CHANNEL:
          - nixos-20.09
          - nixos-21.05
          - nixos-21.11
