stages:
  - build

build:
  stage: build
  image: nixpkgs/nix:nixos-23.05
  script: nix-shell --run ./ci.sh
  parallel:
    matrix:
      - NIXPKGS_CHANNEL: nixos-unstable
        IMAGE_TAG: latest
      - NIXPKGS_CHANNEL:
          - nixos-24.05
          - nixos-24.11
          - nixos-25.05
