image: nixos/nix:latest

stages:
  - build
  - publish

before_script:
  - nix-shell --run .gitlab/docker-login

nixos-unstable:
  extends: .build
  variables:
    NIXPKGS_CHANNEL: nixos-unstable

nixos-18.09:
  extends: .build
  variables:
    NIXPKGS_CHANNEL: nixos-18.09

# ---- templates ---

.build:
  stage: build
  script:
    - nix-shell --run ./build
    - nix-shell --run .gitlab/push-master
  variables:
    NIX_PATH: "nixpkgs=channel:${NIXPKGS_CHANNEL}"
    REGISTRY_URL: "${CI_REGISTRY_IMAGE}/${NIXPKGS_CHANNEL}"

