image: nixos/nix:latest

stages:
  - build

nixos-unstable:
  stage: build
  script: nix-shell --run ./.gitlab-ci.sh
  variables:
    NIXPKGS_CHANNEL: nixos-unstable
    IMAGE_TAG: latest

nixos-19.03:
  stage: build
  script: nix-shell --run ./.gitlab-ci.sh
  variables:
    NIXPKGS_CHANNEL: nixos-19.03

nixos-19.09:
  stage: build
  script: nix-shell --run ./.gitlab-ci.sh
  variables:
    NIXPKGS_CHANNEL: nixos-19.09
