language: nix

nix: 2.3.6

matrix:
  include:
  - name: nixos-unstable
    env: NIXPKGS_CHANNEL=nixos-unstable IMAGE_TAG=latest
  - name: nixos-20.03
    env: NIXPKGS_CHANNEL=nixos-20.03

script:
  - NIX_PATH=channel:$NIXPKGS_CHANNEL nix-shell --run ./.travis.sh
