name: Nix
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: nix-community
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: ./build
        env:
          - NIX_PATH=channel:nixos-unstable
